config/routes.rb
HotelsApp::Application.routes.draw do
 

  resources :users
  resources :hotels
resources :sessions, only: [:new, :create, :destroy]

 root to: 'static_pages#home'
  
 match '/hotels',  to: 'hotels#index'
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

app/models/address.rb
class Address < ActiveRecord::Base
  attr_accessible :city, :country, :state, :street
  belongs_to :hotel
end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
  attr_accessible :star_rating, :rates_count, :title
  has_one  :address
  has_many :user_hotels
  has_many :rooms
  has_many :users, through: :user_hotels
  	validates :title, presence: true, 
 					length: { maximum: 50 }
	
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :link, :room_id
end

app/models/room.rb
class Room < ActiveRecord::Base
  attr_accessible :hotel_id, :price, :room_type, :breakfast
  belongs_to :hotel
end

app/models/user.rb
class User < ActiveRecord::Base
attr_accessible :name, :email, :password, :password_confirmation

has_secure_password
has_many :user_hotels
  has_many :hotels, through: :user_hotels

  before_save { email.downcase! }
  before_save :create_remember_token

 validates :name, 	presence: true, 
 					length: { maximum: 50 }
 VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
 validates :email, 	presence: true, 
 					format: { with: VALID_EMAIL_REGEX },
 					uniqueness: {case_sensitive: false}
 validates :password, 	presence: true,
					 	length: { minimum: 6 }
 validates :password_confirmation, presence: true
 private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
 		end

app/models/user_hotel.rb
class UserHotel < ActiveRecord::Base
  attr_accessible :comment, :rating, :user_id, :hotel_id
  belongs_to :user
  belongs_to :hotel
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper

  # Force signout to prevent CSRF attacks
  def handle_unverified_request
    sign_out
    super
  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  def index
    @hotels = Hotel.all
  end

  def show
    @hotel = Hotel.find(params[:id])
   @address_attr = Address.find_by_hotel_id(params[:id]).attributes
   @address_ = {"country" => @address_attr['country'],
                "state" => @address_attr['state'],
                "city" => @address_attr['city'],
                "street" => @address_attr['street'] }
    @address2 = []
    @address_.each do  |a|  
      if !a[1].blank? then @address2.push(a[1])
      end
        end
      @address2 = @address2.join(", ")
  
   
  
  
end
 

  def new
    @hotel = Hotel.new
    @address = Address.new
    @userhotel = UserHotel.new
  end

  def create

    @hotel = Hotel.new(params[:hotel].merge(:star_rating => params[:user_hotel][:rating]))
    @hotel.address = Address.new(params[:address])
      
  if @hotel.save
    @user_hotel = UserHotel.new(params[:user_hotel].merge(:hotel_id => @hotel[:id], :user_id => current_user.id))
    @user_hotel.save
    
    
    redirect_to @hotel
  else
    render :action => 'new'
  end
end

def edit
  @hotel = Hotel.find(params[:id])
  @mark = UserHotel.find_by_hotel_id_and_user_id(params[:id], current_user.id)[:rating]
  @address = Address.find_by_hotel_id(params[:id])
end

def update 

  @hotel = Hotel.find(params[:id])
@userhotel = UserHotel.find_by_hotel_id_and_user_id(params[:id], current_user.id)
@hotel.star_rating += (params[:user_hotel][:rating].to_i - @userhotel[:rating].to_i)
@hotel.address = Address.find_by_hotel_id(params[:id])
  if (@hotel.update_attributes(params[:hotel], :star_rating => @hotel.star_rating) 
     @userhotel.update_attributes(params[:user_hotel])
     @hotel.address.update_attributes(params[:address]))

    flash[:success] = "Information updated"
    redirect_to @hotel
  else
    @hotel.star_rating += @user_hotel.rating
    render 'edit'
  end
end

#def update
#    @hotel = Hotel.find(params[:id])
  #  @hotel.address = Address.new(params[:address])
  #    if @hotel.address.update(params[:address])
  #   render :action => 'new'
 # else
  #  render :action => 'new'
 # end
#end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
 def new
  end

  def create
    user = User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
  	@user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
    	sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Hotels App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hotels/edit.html.erb
<%= form_for(@hotel, url: hotel_path(@hotel), html: { method: :PUT }) do |f| %>
  <% if @hotel.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@hotel.errors.count, "error") %> prohibited
      this hotel from being saved:</h2>
    <ul>
    <% @hotel.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :user_hotel, :rating %><br>
    <%= text_field :user_hotel, :rating,  value:  @mark  %>
  </p>
 <p>
    <%= f.label :address, :country %><br>
    <%= text_field :address, :country, value: @address[:country]%>
  </p>
   <p>
    <%= f.label :address, :state %><br>
    <%= text_field :address, :state, value: @address[:state]%>
  </p>
   <p>
    <%= f.label :address, :city %><br>
    <%= text_field :address, :city, value: @address[:city]%>
  </p>
   <p>
    <%= f.label :address, :street %><br>
    <%= text_field :address, :street, value: @address[:street]%>
  </p>
<!-- hidden_field_tag :model_id, params[:model_id] -->

 
  <p>
    <%= f.submit %>
  </p>
<% end %>
 
<%= link_to 'Back', hotels_path %>

app/views/hotels/index.html.erb
<% provide(:title, "Hotels") %>
<div class="row">
  <aside class="span4">
    <section>
      <h3>

      	We have information about these hotels

      	<%  @hotels.each do |h|  %>
      	<%= link_to h.title, hotel_path(h.id) %>
      	<br>
      	<% end %>
      </h3>
      </section>
  </aside>
</div>

app/views/hotels/new.html.erb
<% provide(:title, 'New hotel') %>
<h1>Add a hotel</h1>

<div class="row">
  <div class="span6 offset3">


<%= form_tag :action => 'create' %>

<p>
  Hotel title (necessary):
  <%= text_field :hotel, :title %>
</p>
<p>
  Rate this hotel (necessary):
  <%= text_field :user_hotel, :rating %>
</p>
<p>
  You can leave a short description
  <%= text_field :user_hotel, :comment %>
</p>

Please fill in the address  
<p>
  Country:
  <%= text_field :address, :country %>
</p>
<p>
  State:
  <%= text_field :address, :state %>
</p>
<p>
  City:
  <%= text_field :address, :city %>
</p>
<p>
  Street:
  <%= text_field :address, :street %>
</p>

<p>
  <%= submit_tag 'Create' , class: "btn btn-large btn-primary" %>
</p>
<%= form_tag %>


  </div>
</div>

app/views/hotels/show.html.erb
<% provide(:title, @hotel.title) %>
<div class="row">
 
    <section>
      <h1>
      	<%= @hotel.title %>
      </h1>
      	<h2> <% if !@address2.blank?     %>
      		<%=  "Address:" %>

      		<%= @address2  %> 
		 	<%  else %>
		 <%= "We have no address yet for this hotel. You can add it " %>
			<%= link_to 'here:', edit_hotel_path(@hotel.id) %>		
<%  end %>
		
		<h2>
      </section>
 
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Developed by Oleg Trofimenko
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://isport.ua/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "sample app", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", '#' %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", '#' %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
    </div>
  </body>
</html>

app/views/shared/_error_messaged.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
    <h1>About Us</h1>
    <p>     
      It is simple hotels application.
    </p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contacts is under construction
  
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
    <h1>Help</h1>
    <p>
      Get help
    </p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>Welcome to the Hotels App</h1>

  <h2>
  
    This is the home page for the
    hotels advisor application.
  </h2>

 <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "google"), 'http://google.com/' %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
      	<%= @user.name %>
      </h1>
      </section>
  </aside>
</div>